version: '3.9'
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200

    kibana:
        image: docker.elastic.co/kibana/kibana:7.16.0
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://localhost:9200
        depends_on:
            - elastic
